<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;">EDUNET FOUNDATION-Classroom Exercise Notebook</span>

<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;"> Lab 2: Perform Indexing , Slicing and Broadcasting in NumPy </span>

<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Program 1 -  Indexing in NumPy</span>

In [3]:
import numpy as np
arr=np.arange(1,10,2) 
print("Elements of array: ",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ",arr1)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


<span style="color:black;font-size: 15px; font-family: Arial; font-weight: bold;"> Indexing in 1 dimension </span>

In [4]:
import numpy as np 
arr1=np.arange(4)
print("Array arr11:",arr1)
print("Element at index 0 of arri is: ", arr1[0])
print("Element at index 1 of arr1 is: ", arr1[1])

Array arr11: [0 1 2 3]
Element at index 0 of arri is:  0
Element at index 1 of arr1 is:  1


<span style="color:black;font-size: 15px; font-family: Arial; font-weight: bold;"> Indexing in 2 Dimensions </span>

In [5]:
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("Element at eth row and eth column of arr1 is:",arr1[0,0]) 
print("Element at 1st row and 2nd column of arr1 is:", arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at eth row and eth column of arr1 is: 0
Element at 1st row and 2nd column of arr1 is: 6


<span style="color:black;font-size: 15px; font-family: Arial; font-weight: bold;"> Indexing in 3 Dimensions </span>

In [6]:
import numpy as np 
arr=np.arange(12) 
arr1=arr.reshape(2,2,3)
print("Array arr1:\n", arr1) 
print("Element:", arr1[1,0,2])

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 8


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Program 2 - Slicing an Array </span>

<span style="color:black;font-size: 15px; font-family: Arial; font-weight: bold;"> Slicing 1D NumPy Arrays </span>

In [7]:
import numpy as np
arr = np.arange(6)
print("array arr:",arr) 
print("sliced element of array: ", arr[1:5])

array arr: [0 1 2 3 4 5]
sliced element of array:  [1 2 3 4]


<span style="color:black;font-size: 15px; font-family: Arial; font-weight: bold;"> Slicing 2D NumPy Arrays </span>

In [8]:
import numpy as np
arr =np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1: \n",arr1)
print("\n")
print("elements of 1st row and 1st column upto last column \n", arr1[1:,1:4])

Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


elements of 1st row and 1st column upto last column 
 [[ 5  6  7]
 [ 9 10 11]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Program 3 - NumPy broadcasting </span>

In [9]:
import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar to the array
scalar = 10
result = arr + scalar

print("Original Array:")
print(arr)
print("\nResult after Broadcasting:")
print(result)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result after Broadcasting:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
