<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;"> EDUNET FOUNDATION-Self Practice Solution Notebook</span>

<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Lab 2: Solutions Notebook</span>

<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 1: Array Creation and Indexing. </span>

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;">1 Create a NumPy array containing the numbers from 0 to 9. </span> 

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 2 Print the element at index 3. </span> 

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 3 Print the last element of the array. </span> 

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 4 Create a 2D array with shape (3, 3) containing consecutive numbers starting from 1. </span> 

 <span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 5 Print the element at row 2 and column 1 of the 2D array.</span> 

In [3]:
import numpy as np

# Exercise 1
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
element_at_index_3 = array1[3]
last_element = array1[-1]
array2d = np.arange(1, 10).reshape(3, 3)
element_row2_col1 = array2d[2, 1]

print("Array 1:", array1)
print("Element at Index 3:", element_at_index_3)
print("Last Element:", last_element)
print("2D Array:")
print(array2d)
print("Element at Row 2, Column 1:", element_row2_col1)


Array 1: [0 1 2 3 4 5 6 7 8 9]
Element at Index 3: 3
Last Element: 9
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at Row 2, Column 1: 8


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 2 : Slicing and Broadcasting </span>

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;">1 Create a NumPy array containing the numbers from 1 to 10. </span> 

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 2 Use slicing to extract a subarray containing the elements from index 2 to 6. </span> 

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 3 Multiply the subarray by 2 using broadcasting. </span> 

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 4 Create a 2D array with shape (4, 3) containing consecutive numbers starting from 1. </span> 

 <span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> 5 Slice the first two rows and the last two columns of the 2D array.</span> 

In [5]:
import numpy as np

# Exercise 2
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
subarray = array1[2:7]
multiplied_subarray = subarray * 2
array2d = np.arange(1, 13).reshape(4, 3)
sliced_subarray2d = array2d[:2, -2:]

print("Array 1:", array1)
print("Subarray:", subarray)
print("Multiplied Subarray:", multiplied_subarray)
print("2D Array:")
print(array2d)
print("Sliced Subarray 2D:")
print(sliced_subarray2d)


Array 1: [ 1  2  3  4  5  6  7  8  9 10]
Subarray: [3 4 5 6 7]
Multiplied Subarray: [ 6  8 10 12 14]
2D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Sliced Subarray 2D:
[[2 3]
 [5 6]]
