<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;">EDUNET FOUNDATION-Classroom Exercise Notebook</span>

<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;"> Lab 1 - Create NumPy array and Perform I/O Function with NumPy </span>

<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Exercise 1 - Create an array </span>

In [4]:
import numpy as np

my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> Create 0-D Arrays </span>

In [9]:
import numpy as np
arr = np.array (42)
print(arr)

42


<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> Create 1-D Arrays </span>

In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> Create 2-D Arrays </span>

In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> Create 3-D Arrays </span>

In [13]:
import numpy as np
arr1= np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]], [[76,33], [20,18]]]) 
print("Create 3-d array: ", arr1)

Create 3-d array:  [[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Exercise 2 - Perform I/O with NumPy </span>

<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> numpy.save() </span>

In [15]:
import numpy as np 
a= np.array([1,2,3,4,5])
np.save('outfile',a)

In [16]:
import numpy as np
b = np.load('outfile.npy')
print(b)

[1 2 3 4 5]


<span style="color:black;font-size: 20px; font-family: Arial; font-weight: bold;"> savetxt() </span>

In [17]:
import numpy as np
a = np.array([1,2,3,4,5])
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
print(b)

[1. 2. 3. 4. 5.]
