<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;">EDUNET FOUNDATION-Classroom Exercise Notebook</span>

<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;"> Lab 4 - Performing statistical function in NumPy </span>

In [1]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
print("Mean:", mean)

Mean: 30.0


In [2]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
median = np.median(data)
print("Median:", median)

Median: 30.0


In [3]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

Standard Deviation: 14.142135623730951


In [4]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
variance = np.var(data)
print("Variance:", variance)

Variance: 200.0


In [5]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
percentile_75 = np.percentile(data, 75)
print("75th Percentile:", percentile_75)

75th Percentile: 40.0


In [6]:
import numpy as np

data = np.array([10, 5, 20, 15, 30])
minimum = np.amin(data)

print("Array:", data)
print("Minimum Value:", minimum)

Array: [10  5 20 15 30]
Minimum Value: 5


In [7]:
import numpy as np

matrix = np.array([[10, 5, 8],
                   [15, 7, 12],
                   [20, 25, 18]])

minimum_along_columns = np.amin(matrix, axis=0)
minimum_along_rows = np.amin(matrix, axis=1)

print("Matrix:")
print(matrix)
print("Minimum Along Columns:", minimum_along_columns)
print("Minimum Along Rows:", minimum_along_rows)

Matrix:
[[10  5  8]
 [15  7 12]
 [20 25 18]]
Minimum Along Columns: [10  5  8]
Minimum Along Rows: [ 5  7 18]
